== Creating Slides

Build *training slides* with one script invocation (which contains all the link:#neo4j-training-classes[steps listed below]): 

Run `./create_training_slides.sh`

== Detailed Steps

=== AsciiDoc -> HTML

This is what you install (in your terminal):

- Install asciidoctor and dependencies
[source,bash]
----
gem install bundler
bundle install
----

On Ubuntu (tested with 16.04) you don't need to use gem/bundle, instead install these packages

[source,bash]
----
sudo apt-get install asciidoctor ruby-tilt ruby-thread-safe ruby-haml
----

For a unkown reason on Ubuntu you might need to set attribute `encoding=utf-8` either in the adoc files or by amending `-a encoding=utf-8` to the invokation of asciidoctor.

Make sure you're using asciidoctor 1.5.1

- execute asciidoctor to produce Deck.js HTML5 output from the AsciiDoc source files

Test it with:

[source,bash]
----
./run.sh content/demo/index.adoc
#equivalent to
asciidoctor -T ./asciidoctor-backends/haml/deckjs -a allow-uri-read -a presenter="Your Name"  content/demo/index.adoc
----

=== Open HTML File

- open the resulting HTML file
[source,bash]
----
./http content/demo/index.html
----

http://neo4j-contrib.github.io/asciidoc-slides/content/demo/index.html[Slide Demo on GH-Pages]

=== AsciiDoc -> PDF

Renders the document to a temporary file, without creating intermediate steps for bullets.
Then generates PDF from that using an "screencapture" app. This will get better soon.

[source,bash]
----
./pdf.sh content/demo/index.adoc
----

== Neo4j Training Classes

=== Content Git Submodule

Content available in a *separate, private* GitHub repository https://github.com/neo-technology/training-slides

which is integrated in this project as *git submodule*.

Use `git submodule init` and `git submodule update` to pull the latest versoin.

Then the training content is found under:

`content/training/[intro,cypher,production,modeling,import]/[classroom,online]/index.adoc`

=== Build Training HTML

Easiest to just run `./create_training_slides.sh`

build **Movies Intro** training with:

----
./training.sh 
# or
./training.sh [path/to/training.adoc] ["Trainer Name"] [trainer@email.com] [@trainer]
----

=== Open Training in Browser

The easiest way to start the training is to start a webserver and open the training on a http url.

For example run a SimpleHTTPServer with python.
This is wrapped in a shell scripts for unix users.

on Linux:

[source,bash]
----
./http .
# or a concrete training
./http content/training/intro/intro-cypher-movies/training-intro-cypher-movies.html
----

== In Browser Key-Bindings during the Training

There are a couple of shortcuts you can use as a trainer to help during the training this is a summery of the most common:

* g: show a window to quickly go to a slide.
* m: show an overview of your presentation, be able to click a slide to goto the selected slide.
* n: show presenter notes
* p: clone the presentation to a presenter-deck (with next slide and presenter notes) and a master.
