== Producing html

This is what you install (in your terminal):

- Install asciidoctor and dependencies
[source,bash]
----
gem install bundler
bundle install
----

Make sure you're using at least asciidoctor 1.5.0

- execute asciidoctor to produce Deck.js HTML5 output from the asciidoc source files
[source,bash]
----
asciidoctor -T ./asciidoctor-backends/haml/deckjs -a allow-uri-read -a presenter="Your Name"  content/demo/index.adoc
----

or

----
./run.sh content/demo/index.adoc
----

- open the resulting HTML file
[source,bash]
----
open content/demo/index.html
----

see: http://neo4j-contrib.github.io/asciidoc-slides/content/demo/index.html[Slide Demo]

- generate PDF from HTML.
[source,bash]
----
./pdf.sh content/demo/index.html content/demo/intro.pdf
----

=== Neo4j Training Classes

Available in a separate, private GitHub repository https://github.com/neo-technology/training-slides

which is integrated in this project as git submodule.

Use `git submodule init` and `git submodule update` to pull the latest versoin.

Then the training content is found under:

`content/training/[intro,cypher,production,modeling,import]/[classroom,online]/index.adoc`

build **intro** training with

----
./training.sh
----

see: http://neo4j-contrib.github.io/asciidoc-slides/content/training/intro/classroom/index.html[Training Demo]

== Run training

The easiest way to start the training is to start a webserver and open the training on a http url.

For example run a SimpleHTTPServer with python.
This is wrapped in a shell scripts for unix users.

on Linux:

[source,bash]
----
./http content/training/intro/classroom/index.html
----

== keymappings during the training

There are a couple of shortcuts you can use as a trainer to help during the training this is a summery of the most common:

* g: show a window to quickly go to a slide.
* m: show an overview of your presentation, be able to click a slide to goto the selected slide.
* n: show presenter notes
* c: clone the presentation to a presenter-deck (with next slide and presenter notes) and a master.
